version: '3.9'

services:
  db_mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat_system

  application:
    build: .
    hostname: rails
    command: /entrypoint.sh
    ports:
      - "3000:3000"
      - "1234:1234"
    depends_on:
      - db_mysql
      - elasticsearch
    volumes:
      - .:/chat_system
    tty: true
    stdin_open: true
    environment:
      WAIT_HOSTS: db_mysql:3305, elasticsearch:9200, rabbitmq:5672
      APPLICATION_PORT: 3000
      DEBUGGING_PORT: 1234

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - "9200:9200"
#    environment:
#      - discovery.type=single-node

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    hostname: rabbitmq
#    restart: on-failure
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"