require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/application_chats", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ApplicationChat. As you add validations to ApplicationChat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ApplicationChat.create! valid_attributes
      get application_chats_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      application_chat = ApplicationChat.create! valid_attributes
      get application_chat_url(application_chat)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_application_chat_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      application_chat = ApplicationChat.create! valid_attributes
      get edit_application_chat_url(application_chat)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ApplicationChat" do
        expect {
          post application_chats_url, params: { application_chat: valid_attributes }
        }.to change(ApplicationChat, :count).by(1)
      end

      it "redirects to the created application_chat" do
        post application_chats_url, params: { application_chat: valid_attributes }
        expect(response).to redirect_to(application_chat_url(ApplicationChat.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ApplicationChat" do
        expect {
          post application_chats_url, params: { application_chat: invalid_attributes }
        }.to change(ApplicationChat, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post application_chats_url, params: { application_chat: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested application_chat" do
        application_chat = ApplicationChat.create! valid_attributes
        patch application_chat_url(application_chat), params: { application_chat: new_attributes }
        application_chat.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the application_chat" do
        application_chat = ApplicationChat.create! valid_attributes
        patch application_chat_url(application_chat), params: { application_chat: new_attributes }
        application_chat.reload
        expect(response).to redirect_to(application_chat_url(application_chat))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        application_chat = ApplicationChat.create! valid_attributes
        patch application_chat_url(application_chat), params: { application_chat: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested application_chat" do
      application_chat = ApplicationChat.create! valid_attributes
      expect {
        delete application_chat_url(application_chat)
      }.to change(ApplicationChat, :count).by(-1)
    end

    it "redirects to the application_chats list" do
      application_chat = ApplicationChat.create! valid_attributes
      delete application_chat_url(application_chat)
      expect(response).to redirect_to(application_chats_url)
    end
  end
end
